function [xp,yp] = check_NR_symbolic_pos(in1,dx,dy,X,Y)
%CHECK_NR_SYMBOLIC_POS
%    [XP,YP] = CHECK_NR_SYMBOLIC_POS(IN1,DX,DY,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    04-Feb-2018 16:40:51

P_1 = in1(1,:);
P_2 = in1(2,:);
P_3 = in1(3,:);
P_4 = in1(4,:);
P_5 = in1(5,:);
P_6 = in1(6,:);
xp = P_1+X+P_3.*dy+dx.*(P_2+1.0);
if nargout > 1
    yp = P_4+Y+P_5.*dx+dy.*(P_6+1.0);
end
