function J = JacobianStandard_p2(in1,in2,dx,dy,X,Y)
%JACOBIANSTANDARD_P2
%    J = JACOBIANSTANDARD_P2(IN1,IN2,DX,DY,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    17-Jan-2018 17:11:34

A_2 = in1(:,2);
A_3 = in1(:,3);
A_4 = in1(:,4);
A_5 = in1(:,5);
A_6 = in1(:,6);
A_7 = in1(:,7);
A_8 = in1(:,8);
A_9 = in1(:,9);
A_10 = in1(:,10);
A_11 = in1(:,11);
A_12 = in1(:,12);
A_13 = in1(:,13);
A_14 = in1(:,14);
A_15 = in1(:,15);
A_16 = in1(:,16);
P_1 = in2(1,:);
P_2 = in2(2,:);
t2 = P_1+X+dx;
t3 = floor(t2);
t4 = t3-1.0;
t6 = floor(t2);
t5 = P_1+X+dx-t6;
t7 = t5.^2;
t8 = P_2+Y+dy;
t9 = floor(t8);
t10 = P_2+Y+dy-t9;
t11 = t10.^2;
t12 = floor(t8);
t13 = t12-1.0;
J = [-A_2.*t4-t10.*(A_6.*t4+A_7.*t4.*t5.*2.0+A_8.*t4.*t7.*3.0)-t11.*(A_10.*t4+A_11.*t4.*t5.*2.0+A_12.*t4.*t7.*3.0)-A_3.*t4.*t5.*2.0-A_4.*t4.*t7.*3.0-t10.*t11.*(A_14.*t4+A_15.*t4.*t5.*2.0+A_16.*t4.*t7.*3.0),-t13.*(A_5+A_6.*t5+A_7.*t7+A_8.*t5.*t7)-t10.*t13.*(A_9+A_10.*t5+A_11.*t7+A_12.*t5.*t7).*2.0-t11.*t13.*(A_13+A_14.*t5+A_15.*t7+A_16.*t5.*t7).*3.0];
