function M = Mat2Vec(in1)
%MAT2VEC
%    M = MAT2VEC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    22-Feb-2018 16:46:48

A11 = in1(1);
A12 = in1(4);
A13 = in1(7);
A21 = in1(2);
A22 = in1(5);
A23 = in1(8);
M = [A13,A11-1.0,A12,A23,A21,A22-1.0];
